import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import Header from './landing-components/heading'
import SiteFooter from './landing-components/footer'
import {Box, DarkMode} from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers>
              <DarkMode>
                  <Header />
                  <Box />
                  {children}
                  <SiteFooter />
              </DarkMode>
          </Providers>
        </body>
    </html>
  )
}
