name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' # On push to tag starting with v
    paths:
      - 'labs/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./labs
        push: true
        tags: |
            ghcr.io/${{ github.repository_owner }}/labs:stable
            ghcr.io/${{ github.repository_owner }}/labs:${{ github.ref_name }}
